# Generated by Django 3.1 on 2020-08-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
